import Head from 'next/head';
import styled from 'styled-components';

const StyledDiv = styled.div`
  background-color: ${({ theme }) => theme.colors.primary};
  width: 100px;
  height: 100px;
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <StyledDiv />
      </main>
    </>
  );
}
