import Navigation from 'components/organisms/Navigation/Navigation';
import Head from 'next/head';
import Hero from 'components/organisms/Hero/Hero';
import About from 'components/organisms/About/About';
import Services from 'components/organisms/Services/Services';
import Statistics from 'components/organisms/Statistics/Statistics';
import Entries from 'components/organisms/Entries/Entries';
import Contact from 'components/organisms/Contact/Contact';
import Footer from 'components/organisms/Footer/Footer';

export default function Home() {
  return (
    <>
      <Head>
        <title>Kwadrans dla mowy | Pracownia neurologopedyczno-lingwistyczna</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <main>
        <Hero />
        <About />
        <Services />
        <Statistics />
        <Entries />
        <Contact />
        <Footer />
      </main>
    </>
  );
}
